#!/usr/bin/env python3
"""Writes the symbol table of a static JDK program for the guest: the functions that dlsym()
(compat/wasm_compat.c) finds by name, as the JDK's native code looks them up at run time.

    gen-symtab.py OUT.c INPUT.o|INPUT.a...

The table has every function of the inputs whose name the JDK looks up (JNI functions, the
JNI_OnLoad_<lib> of each static library, the JVM's and the libraries' entry points), and a few
functions of the C library that the JDK looks up with dlsym(RTLD_DEFAULT, ...).
"""
import re
import subprocess
import sys

NM = "llvm-nm-19"
WANTED = re.compile(r"^(Java_|JNI_OnLoad_|JNI_OnUnload_|Agent_OnLoad_|Agent_OnAttach_|Agent_OnUnload_"
                    r"|JNI_CreateJavaVM$|JNI_GetDefaultJavaVMInitArgs$|JNI_GetCreatedJavaVMs$"
                    r"|JVM_|JDK_|JIMAGE_|ZIP_|JNU_|jdwpTransport_OnLoad|GetStringPlatformChars$|VerifyClassForMajorVersion$)")
# looked up with dlsym(RTLD_DEFAULT, name): name -> the C library's function
LIBC = {
    "copy_file_range": "copy_file_range",
    "unlinkat": "unlinkat",
    "renameat": "renameat",
    "openat64": "openat",
    "fstatat64": "fstatat",
    "fdopendir": "fdopendir",
    "statx": "statx",
    "sched_getcpu": "sched_getcpu",
    "pthread_setname_np": "pthread_setname_np",
    "pthread_condattr_setclock": "pthread_condattr_setclock",
}


def main():
    out, inputs = sys.argv[1], sys.argv[2:]
    names = set()
    if inputs:
        nm = subprocess.run([NM, "--defined-only", "--extern-only", "--format=posix", *inputs],
                            capture_output=True, text=True)
        for line in nm.stdout.splitlines():
            parts = line.split()
            if len(parts) >= 2 and parts[1] in ("T", "W") and WANTED.match(parts[0]):
                names.add(parts[0])
    table = {n: n for n in names}
    table.update(LIBC)
    lines = ["/* Generated by tools/gen-symtab.py: the functions dlsym() finds. */", ""]
    for target in sorted(set(table.values())):
        lines.append("extern void %s(void);" % target)
    lines += ["", "struct jdk_wasm_symbol { const char *name; void *addr; };",
              "const struct jdk_wasm_symbol __jdk_wasm_symbols[] = {"]
    for name in sorted(table):  # strcmp order (ASCII)
        lines.append('  {"%s", (void *)&%s},' % (name, table[name]))
    lines += ["};", "const unsigned __jdk_wasm_symbol_count = %d;" % len(table), ""]
    with open(out, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
