#!/usr/bin/env python3
"""Writes ffi_calls.c: the call stubs of the wasm32 libffi (ffi/ffi.h) and their sorted table.

    gen-ffi-calls.py OUT.c [CLASSES_DIR...]

A stub calls a function pointer with one wasm signature: return type, then "_", then a type per
argument, each one of i (i32), j (i64), f (f32), d (f64), v (void, results only). The stubs are
- every signature of up to GENERIC_ARGS arguments,
- every JNI-shaped signature (two i32s, JNIEnv* and jobject/jclass, first) of up to JNI_EXTRA more,
- the JNI signature of every native method in the class files under CLASSES_DIRs (the class
  library: these are all the native methods HotSpot can call, as the launcher is static).
"""
import itertools
import os
import struct
import sys

GENERIC_ARGS = 3
JNI_EXTRA = 4
ARG_TYPES = "ijfd"
RESULT_TYPES = "vijfd"
CTYPE = {"i": "int32_t", "j": "int64_t", "f": "float", "d": "double", "v": "void"}


def parse_array_aware(desc):
    """Parameter types of a method descriptor, as wasm types (arrays and objects are i32)."""
    out = []
    i = 1
    while desc[i] != ")":
        c = desc[i]
        if c == "[":
            while desc[i] == "[":
                i += 1
            if desc[i] == "L":
                i = desc.index(";", i)
            i += 1
            out.append("i")
        elif c == "L":
            i = desc.index(";", i) + 1
            out.append("i")
        else:
            out.append({"J": "j", "F": "f", "D": "d"}.get(c, "i"))
            i += 1
    r = desc[i + 1]
    return {"V": "v", "J": "j", "F": "f", "D": "d"}.get(r, "i"), out


def native_methods(path):
    """(name, descriptor, static) of each native method of a class file."""
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"\xca\xfe\xba\xbe":
        return []
    pos = 10
    count = struct.unpack_from(">H", data, 8)[0]
    utf8 = {}
    i = 1
    while i < count:
        tag = data[pos]
        if tag == 1:
            n = struct.unpack_from(">H", data, pos + 1)[0]
            utf8[i] = data[pos + 3:pos + 3 + n].decode("utf-8", "replace")
            pos += 3 + n
        elif tag in (3, 4, 9, 10, 11, 12, 17, 18):
            pos += 5
        elif tag in (5, 6):
            pos += 9
            i += 1
        elif tag in (7, 8, 16, 19, 20):
            pos += 3
        elif tag == 15:
            pos += 4
        else:
            raise ValueError(f"{path}: constant pool tag {tag}")
        i += 1
    pos += 6
    interfaces = struct.unpack_from(">H", data, pos)[0]
    pos += 2 + 2 * interfaces
    for _ in range(2):  # fields, then methods
        n = struct.unpack_from(">H", data, pos)[0]
        pos += 2
        members = []
        for _ in range(n):
            flags, name, desc, attrs = struct.unpack_from(">HHHH", data, pos)
            pos += 8
            for _ in range(attrs):
                length = struct.unpack_from(">I", data, pos + 2)[0]
                pos += 6 + length
            members.append((flags, utf8[name], utf8[desc]))
    return [(name, desc, bool(flags & 0x0008)) for flags, name, desc in members if flags & 0x0100]


def class_sigs(dirs):
    sigs = set()
    for d in dirs:
        for root, _, files in os.walk(d):
            for fn in files:
                if fn.endswith(".class"):
                    for _, desc, _ in native_methods(os.path.join(root, fn)):
                        ret, args = parse_array_aware(desc)
                        sigs.add(ret + "_ii" + "".join(args))
    return sigs


def main():
    out, dirs = sys.argv[1], sys.argv[2:]
    sigs = set()
    for n in range(GENERIC_ARGS + 1):
        for args in itertools.product(ARG_TYPES, repeat=n):
            for r in RESULT_TYPES:
                sigs.add(r + "_" + "".join(args))
    for n in range(JNI_EXTRA + 1):
        for args in itertools.product(ARG_TYPES, repeat=n):
            for r in RESULT_TYPES:
                sigs.add(r + "_ii" + "".join(args))
    from_classes = class_sigs(dirs)
    sigs |= from_classes
    lines = ["/* Generated by tools/gen-ffi-calls.py: the call stubs of the wasm32 libffi. */",
             "#include <stdint.h>", "#include \"ffi.h\"", ""]
    names = {}
    for sig in sorted(sigs):
        ret, args = sig.split("_")
        name = "c_" + sig
        names[sig] = name
        params = ", ".join(CTYPE[a] for a in args) or "void"
        call = "((%s (*)(%s))fn)(%s)" % (CTYPE[ret], params,
                                          ", ".join("*(%s *)a[%d]" % (CTYPE[a], k) for k, a in enumerate(args)))
        if ret == "v":
            body = call + ";"
        elif ret == "i":
            body = "*(ffi_arg *)r = (ffi_arg)%s;" % call
        else:
            body = "*(%s *)r = %s;" % (CTYPE[ret], call)
        lines.append("static void %s(void (*fn)(void), void *r, void **a) { (void)r; (void)a; %s }" % (name, body))
    lines += ["", "struct ffi_wasm_stub { const char *sig; ffi_wasm_call_t call; };",
              "const struct ffi_wasm_stub ffi_wasm_stubs[] = {"]
    # strcmp order: Python's str order is the same for these ASCII strings
    for sig in sorted(sigs):
        lines.append('  {"%s", %s},' % (sig, names[sig]))
    lines += ["};", "const unsigned ffi_wasm_stub_count = %d;" % len(sigs), ""]
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"{out}: {len(sigs)} call stubs ({len(from_classes)} signatures of native methods)")


if __name__ == "__main__":
    main()
