#!/usr/bin/env python3
"""Embeds data files as C strings.

    tools/gen-data.py OUT.c NAME=FILE...
"""
import sys

out = open(sys.argv[1], 'w')
out.write('/* generated by tools/gen-data.py */\n')
for arg in sys.argv[2:]:
    name, path = arg.split('=', 1)
    data = open(path, 'rb').read()
    out.write('const char %s[] =\n' % name)
    for i in range(0, len(data), 80):
        chunk = data[i:i + 80]
        out.write('  "' + ''.join('\\x%02x' % b for b in chunk) + '"\n')
    out.write(';\n')
out.close()
