#!/usr/bin/env python3
"""Writes src/constants_gen.inc: the Define*Constants functions of Node's
src/node_constants.cc and DefineZlibConstants of src/node_zlib.cc, as C.

    tools/gen-constants.py NODE_SRC OUT
"""
import re
import sys

node, out_path = sys.argv[1], sys.argv[2]
src = open(node + '/src/node_constants.cc').read().split('\n')
start = next(i for i, l in enumerate(src) if l.startswith('void DefineErrnoConstants'))
end = next(i for i, l in enumerate(src) if l.startswith('void CreatePerContextProperties'))
out = ['/* generated by tools/gen-constants.py from Node\'s node_constants.cc and node_zlib.cc */']
skip = False
for l in src[start:end]:
    if l.startswith('void DefineWindowsErrorConstants'):
        skip = True
    if skip:
        if l.startswith('}'):
            skip = False
        continue
    m = re.match(r'void (Define\w+)\(Local<Object> target\) \{', l)
    if m:
        out.append('static void %s(JSContext *ctx, JSValue target) {' % m.group(1))
        continue
    out.append(l.replace('NODE_DEFINE_CONSTANT(target,', 'DEF(target,')
                .replace('NODE_DEFINE_STRING_CONSTANT(target,', 'DEF_STR(target,'))
zl = open(node + '/src/node_zlib.cc').read().split('\n')
zs = next(i for i, l in enumerate(zl) if l.startswith('void DefineZlibConstants'))
ze = next(i for i in range(zs, len(zl)) if zl[i].startswith('}'))
for l in zl[zs:ze + 1]:
    if l.startswith('void DefineZlibConstants'):
        out.append('static void DefineZlibConstants(JSContext *ctx, JSValue target) {')
        continue
    out.append(l.replace('NODE_DEFINE_CONSTANT(target,', 'DEF(target,'))
open(out_path, 'w').write('\n'.join(out) + '\n')
