/* js2bc: compiles Node's builtin modules (lib/ and the deps it bundles) to
 * QuickJS bytecode, wrapped in the functions Node calls them with
 * (src/node_builtins.cc), and writes them as a C table.
 *
 *   js2bc OUT.c MANIFEST     MANIFEST: one "id<TAB>path" per line
 *
 * Built for the build machine from the same patched QuickJS the runtime
 * uses: QuickJS bytecode is portable between little-endian targets of the
 * same QuickJS. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "quickjs.h"

static const char *params_for(const char *id) {
  if (!strncmp(id, "internal/per_context/", 21))
    return "exports, primordials, privateSymbols, perIsolateSymbols";
  if (!strcmp(id, "internal/bootstrap/realm"))
    return "process, getLinkedBinding, getInternalBinding, primordials";
  if (!strncmp(id, "internal/bootstrap/", 19) || !strncmp(id, "internal/main/", 14))
    return "process, require, internalBinding, primordials";
  return "exports, require, module, process, internalBinding, primordials";
}

static char *read_file(const char *path, size_t *plen) {
  FILE *f = fopen(path, "rb");
  char *buf;
  long n;
  if (!f) {
    perror(path);
    return NULL;
  }
  fseek(f, 0, SEEK_END);
  n = ftell(f);
  fseek(f, 0, SEEK_SET);
  buf = malloc(n + 1);
  if (fread(buf, 1, n, f) != (size_t)n) {
    perror(path);
    exit(1);
  }
  buf[n] = 0;
  fclose(f);
  *plen = n;
  return buf;
}

typedef struct { char *id; size_t off, len; } Entry;

static int cmp_entry(const void *a, const void *b) {
  return strcmp(((const Entry *)a)->id, ((const Entry *)b)->id);
}

int main(int argc, char **argv) {
  JSRuntime *rt;
  JSContext *ctx;
  FILE *man, *out;
  char line[4096];
  Entry *entries = NULL;
  size_t n = 0, cap = 0, total = 0, i;
  unsigned char *blob = NULL;
  size_t blob_cap = 0;
  int errors = 0;

  if (argc != 3) {
    fprintf(stderr, "usage: js2bc OUT.c MANIFEST\n");
    return 2;
  }
  rt = JS_NewRuntime();
  JS_SetMaxStackSize(rt, 0);
  ctx = JS_NewContext(rt);
  man = fopen(argv[2], "r");
  if (!man) {
    perror(argv[2]);
    return 1;
  }
  while (fgets(line, sizeof(line), man)) {
    char *tab, *id, *path, *src, *wrapped, filename[1024];
    size_t len, wlen, bclen;
    const char *params;
    JSValue obj;
    uint8_t *bc;
    line[strcspn(line, "\r\n")] = 0;
    if (!line[0] || line[0] == '#')
      continue;
    tab = strchr(line, '\t');
    if (!tab) {
      fprintf(stderr, "bad manifest line: %s\n", line);
      return 1;
    }
    *tab = 0;
    id = line;
    path = tab + 1;
    src = read_file(path, &len);
    if (!src)
      return 1;
    params = params_for(id);
    /* "(function (params) {" on the first line keeps line numbers; a
       leading "#!" line is made a comment */
    if (src[0] == '#' && src[1] == '!') {
      src[0] = '/';
      src[1] = '/';
    }
    wlen = len + strlen(params) + 64;
    wrapped = malloc(wlen);
    wlen = snprintf(wrapped, wlen, "(function (%s) {%s\n})", params, src);
    snprintf(filename, sizeof(filename), "node:%s", id);
    obj = JS_Eval(ctx, wrapped, wlen, filename,
                  JS_EVAL_TYPE_GLOBAL | JS_EVAL_FLAG_COMPILE_ONLY);
    free(wrapped);
    free(src);
    if (JS_IsException(obj)) {
      JSValue e = JS_GetException(ctx);
      const char *s = JS_ToCString(ctx, e);
      JSValue st = JS_GetPropertyStr(ctx, e, "stack");
      const char *s2 = JS_ToCString(ctx, st);
      fprintf(stderr, "%s: %s\n%s\n", id, s ? s : "?", s2 ? s2 : "");
      JS_FreeCString(ctx, s);
      JS_FreeCString(ctx, s2);
      JS_FreeValue(ctx, st);
      JS_FreeValue(ctx, e);
      errors++;
      continue;
    }
    bc = JS_WriteObject(ctx, &bclen, obj, JS_WRITE_OBJ_BYTECODE | JS_WRITE_OBJ_STRIP_SOURCE);
    JS_FreeValue(ctx, obj);
    if (!bc) {
      fprintf(stderr, "%s: cannot serialize\n", id);
      return 1;
    }
    if (total + bclen > blob_cap) {
      blob_cap = (total + bclen) * 2;
      blob = realloc(blob, blob_cap);
    }
    memcpy(blob + total, bc, bclen);
    js_free(ctx, bc);
    if (n == cap) {
      cap = cap ? cap * 2 : 256;
      entries = realloc(entries, cap * sizeof(Entry));
    }
    entries[n].id = strdup(id);
    entries[n].off = total;
    entries[n].len = bclen;
    n++;
    total += bclen;
  }
  fclose(man);
  if (errors) {
    fprintf(stderr, "js2bc: %d module(s) failed to compile\n", errors);
    return 1;
  }
  qsort(entries, n, sizeof(Entry), cmp_entry);

  out = fopen(argv[1], "w");
  if (!out) {
    perror(argv[1]);
    return 1;
  }
  fprintf(out, "/* generated by js2bc: Node's builtin modules as QuickJS bytecode */\n");
  fprintf(out, "#include <stdint.h>\n#include <stddef.h>\n\n");
  fprintf(out, "const uint8_t node_builtins_blob[%zu] = {\n", total ? total : 1);
  for (i = 0; i < total; i++) {
    fprintf(out, "%u,", blob[i]);
    if (i % 40 == 39)
      fputc('\n', out);
  }
  if (!total)
    fprintf(out, "0");
  fprintf(out, "\n};\n\n");
  fprintf(out, "const struct { const char *id; uint32_t off, len; } node_builtins_index[] = {\n");
  for (i = 0; i < n; i++)
    fprintf(out, "  { \"%s\", %zu, %zu },\n", entries[i].id, entries[i].off, entries[i].len);
  fprintf(out, "};\nconst int node_builtins_count = %zu;\n", n);
  fclose(out);
  fprintf(stderr, "js2bc: %zu modules, %zu bytes of bytecode\n", n, total);
  JS_FreeContext(ctx);
  JS_FreeRuntime(rt);
  return 0;
}
